### ISSUE TITLE
Compatibility Symfony 4.*

### ISSUE THREAD

**Issue by JeroenMoonen** [fourlabsldn/QBJSParserBundle#14]
Is this bundle compatible with Symfony 4.* ?

**Comment by mowsen** [comment]
All RIGHT. I got this working with Symfony 4 but it took me like 30 hours and a lot of hair pulling haha... (I'm new to Symfony :)

Here's what I did:

1. Create a directory named "lib/FS"
2. Clone both packages fourlabs/qbjs-parser & fourlabs/qbjs-parser-bundle into that folder
3. Update the composer.json file of the two QBJS packages: any symfony/* libraries need to have |^4.0 added to it  (see https://symfony.com/blog/helping-prepare-for-symfony-4-bundle-support)
4. Put this into your app's composer.json:

```
    "repositories": {
      "QBJSParser": {
        "type": "path",
        "url": "lib/FL/QBJSParser",
        "options": {
          "symlink": true
        }
      },
      "QBJSParserBundle": {
        "type": "path",
        "url": "lib/FL/QBJSParserBundle",
        "options": {
          "symlink": true
        }
      }
    } 
```

With this code you allow composer to install those two packages from your local folders.

5. Remove the require line for fourlabs/qbjs-parser in the composer.json of the fourlabs/qbjs-parser-bundle package

6. Go back to your root directory then install both packages like so:
6.1 composer require fourlabs/qbjs-parser @dev
6.2 composer require fourlabs/qbjs-parser-bundle @dev

Do it exactly in that order otherwise it doesn't work (If you try to install the bundle package with the require line in it for qbjs-parser it tries to fetch that dependency from the remote packagist repository and then if fails to install!!!)

7. Add these 3 lines in your config/services.yaml:

```
    FL\QBJSParser\Serializer\JsonDeserializer: "@fl_qbjs_parser.json_deserializer"
    FL\QBJSParserBundle\Service\JsonQueryParser\DoctrineORMParser: "@fl_qbjs_parser.json_query_parser.doctrine_orm_parser"
    FL\QBJSParserBundle\Service\JavascriptBuilders: "@fl_qbjs_parser.javascript_builders"
```

8. In QBJSParserBundle/DependencyInjection/Configuration.php remove ALL occurrences of the cannotBeEmpty() method - otherwise you'll get errors

9. If I didn't forget anything, it should work now. Get the service with:

use FL\QBJSParserBundle\Service\JsonQueryParser\DoctrineORMParser;

function x (DoctrineORMParser $doctrineORMParser) {...

10. Be happy!

I hope I didn't forget anything. Took me two full days to get it working now. Shit I am happy now haha. Have a fine day.

**Comment by galeaspablo** [comment]
Please see https://github.com/fourlabsldn/QBJSParserBundle/releases/tag/1.0.2 
Are all these steps still necessary?

**Comment by mattnraines** [comment]
@galeaspablo Even with those changes I can't get the bundle to install on Symfony 4, because it requires fourlabs/qbjs-parser and that project's composer.json hasn't been updated.

**Comment by mattnraines** [comment]
I think it also needs `->prototype('array')->cannotBeEmpty()` replacing with `->prototype('array')` throughout `DependencyInjection/Configuration.php` as this is causing exceptions in Symfony 4.

**Comment by marczuk** [comment]
I have the same issue like @mattnraines mention, fourlabs/qbjs-parser needs to be updated too.

**Comment by galeaspablo** [comment]
@marczuk thanks for the PR in qbjs-parser. I will close this now, but let me know if you still have issues. Happy to take another PR here and/or there.
